[2024-12-18T19:27:04.563+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-12-18T19:27:04.587+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2024-12-18T19:27:04.596+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T19:27:04.610+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-18T19:27:04.611+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-12-18T19:27:04.612+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-12-18T19:27:04.619+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-18T19:27:04.619+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]>
[2024-12-18T19:27:04.626+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-12-18T19:27:04.627+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-18T19:27:04.633+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-12-18T19:27:04.634+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-18T19:27:04.634+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [queued]>
[2024-12-18T19:27:04.635+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T19:27:04.654+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_all_user_data> on 2024-12-18 19:26:54.527334+00:00
[2024-12-18T19:27:04.667+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-18T19:27:04.667+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiktok_dag', 'fetch_all_user_data', 'manual__2024-12-18T19:26:54.527334+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/tiktok_dag.py', '--cfg-path', '/tmp/tmp6po5ws5g']
[2024-12-18T19:27:04.670+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask fetch_all_user_data
[2024-12-18T19:27:04.669+0000] {standard_task_runner.py:72} INFO - Started process 263 to run task
[2024-12-18T19:27:04.671+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7f2a69185da0>]
[2024-12-18T19:27:04.737+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-18T19:26:54.527334+00:00 [running]> on host 00d1ef865b53
[2024-12-18T19:27:04.819+0000] {taskinstance.py:2384} DEBUG - Clearing XCom data
[2024-12-18T19:27:04.838+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-12-18T19:27:04.871+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-12-18T19:27:04.884+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_dag' AIRFLOW_CTX_TASK_ID='fetch_all_user_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T19:26:54.527334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T19:26:54.527334+00:00'
[2024-12-18T19:27:04.884+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-12-18T19:27:04.885+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-12-18T19:27:04.886+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T19:27:04.903+0000] {tiktok_dag.py:51} INFO - Fetching data for all usernames...
[2024-12-18T19:27:04.917+0000] {tiktok_dag.py:53} INFO - Usernames pulled from XCom: ['mrbeast', 'jadeanna', 'feyenoord']
[2024-12-18T19:27:04.918+0000] {tiktok_dag.py:59} INFO - Fetching data for username: mrbeast
[2024-12-18T19:27:04.919+0000] {tiktok_etl.py:113} INFO - Checking token expiry: {'token': 'Bearer clt.2.2FPqi0MGZIXZZ3clzQTNgyPDqxrcckxt1d-KDYDU4OFr7UMQYh3pHDTym9rRjGwCNZCJ-Oh2yVQv7VAjzbHf8w*0', 'expires_at': 1734447290.981219}
[2024-12-18T19:27:04.919+0000] {tiktok_etl.py:76} INFO - Fetching new token...
[2024-12-18T19:27:04.920+0000] {tiktok_etl.py:86} INFO - Requesting TikTok API with URL: https://open.tiktokapis.com/v2/oauth/token/, Headers: {'Content-Type': 'application/x-www-form-urlencoded'}, Body: {'client_key': 'awppjtwldd6o69ll', 'client_secret': 'prK149Sj8dYCkxgvuXMHkaEMG8pw2yIL', 'grant_type': 'client_credentials'}
[2024-12-18T19:27:04.926+0000] {connectionpool.py:1051} DEBUG - Starting new HTTPS connection (1): open.tiktokapis.com:443
[2024-12-18T19:27:05.875+0000] {connectionpool.py:546} DEBUG - https://open.tiktokapis.com:443 "POST /v2/oauth/token/ HTTP/11" 200 153
[2024-12-18T19:27:05.881+0000] {tiktok_etl.py:102} INFO - New token obtained: Bearer clt.2.2FPqi0MGZIXZZ3clzQTNg5HspN5-HWmf7L0NKoRX0BhEnZIjlUMjWt42QJ8VirRru6kD7hF-JzT4NzPJP7a0RA*0, expires at 2024-12-18 21:27:05.881393
[2024-12-18T19:27:05.883+0000] {tiktok_etl.py:132} INFO - Now in function tiktok_get_user_info, getting mrbeast
[2024-12-18T19:27:05.884+0000] {tiktok_etl.py:139} INFO - Requesting TikTok API with URL: https://open.tiktokapis.com/v2/research/user/info/, Headers: {'Authorization': 'Bearer clt.2.2FPqi0MGZIXZZ3clzQTNg5HspN5-HWmf7L0NKoRX0BhEnZIjlUMjWt42QJ8VirRru6kD7hF-JzT4NzPJP7a0RA*0', 'Content-Type': 'application/json'}, Body: {'username': 'mrbeast'}
[2024-12-18T19:27:05.886+0000] {connectionpool.py:1051} DEBUG - Starting new HTTPS connection (1): open.tiktokapis.com:443
[2024-12-18T19:27:06.646+0000] {connectionpool.py:546} DEBUG - https://open.tiktokapis.com:443 "POST /v2/research/user/info/?fields=display_name%2Cbio_description%2Cis_verified%2Cfollower_count%2Cfollowing_count%2Clikes_count%2Cvideo_count HTTP/11" 200 238
[2024-12-18T19:27:06.649+0000] {tiktok_etl.py:142} INFO - Call is done...
[2024-12-18T19:27:06.650+0000] {tiktok_etl.py:149} INFO - Now in function tiktok_get_user_info, getting resp {'data': {'is_verified': True, 'likes_count': 1057754352, 'video_count': 388, 'bio_description': 'I want to make the world a better place', 'display_name': 'MrBeast', 'follower_count': 106706607, 'following_count': 362}, 'error': {'code': 'ok', 'message': '', 'log_id': '2024121819270568A44ACB1E3D610D50EA'}}
[2024-12-18T19:27:06.654+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/pymongo/_csot.py:119 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
[2024-12-18T19:27:06.656+0000] {logger.py:100} DEBUG - {"message": "Server selection started", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}}
[2024-12-18T19:27:06.659+0000] {logger.py:100} DEBUG - {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}, "remainingTimeMS": 29}
[2024-12-18T19:27:06.661+0000] {logger.py:100} DEBUG - {"message": "Server selection succeeded", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Standalone, rtt: 0.0017599500133655965>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:06.775+0000] {logger.py:100} DEBUG - {"clientId": {"$oid": "676322083e4ccfb0efc84642"}, "message": "Command started", "command": "{\"insert\": \"user_info\", \"ordered\": true, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"Omf/o55IRcWje3hlcw4jgA==\", \"subType\": \"04\"}}}, \"$db\": \"tiktok_db\", \"documents\": [{\"is_verified\": true, \"likes_count\": 1057754352, \"video_count\": 388, \"bio_description\": \"I want to make the world a better place\", \"display_name\": \"MrBeast\", \"follower_count\": 106706607, \"following_count\": 362, \"username\": \"mrbeast\", \"timestamp\": {\"$date\": \"2024-12-18T19:27:06.651Z\"}, \"_id\": {\"$oid\": \"6763220a1cbfed16a5c84643\"}}]}", "commandName": "insert", "databaseName": "tiktok_db", "requestId": 596516649, "operationId": 596516649, "driverConnectionId": 1, "serverConnectionId": 19, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:06.887+0000] {logger.py:100} DEBUG - {"clientId": {"$oid": "676322083e4ccfb0efc84642"}, "message": "Command succeeded", "durationMS": 111.331, "reply": "{\"n\": 1, \"ok\": 1.0}", "commandName": "insert", "databaseName": "tiktok_db", "requestId": 596516649, "operationId": 596516649, "driverConnectionId": 1, "serverConnectionId": 19, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:06.888+0000] {tiktok_etl.py:202} INFO - Data for mrbeast inserted into MongoDB successfully.
[2024-12-18T19:27:06.888+0000] {tiktok_etl.py:177} INFO - TIKTOK request All Other Exception
[2024-12-18T19:27:06.889+0000] {tiktok_etl.py:178} INFO - An unexpected error occurred: name 'file_path' is not defined
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_etl.py", line 158, in tiktok_get_user_info
    context['ti'].xcom_push(key=f'{username}_info_path', value=file_path)
                                                               ^^^^^^^^^
NameError: name 'file_path' is not defined
[2024-12-18T19:27:06.895+0000] {tiktok_dag.py:62} INFO - Successfully fetched data for username: mrbeast
[2024-12-18T19:27:06.896+0000] {tiktok_dag.py:59} INFO - Fetching data for username: jadeanna
[2024-12-18T19:27:06.897+0000] {tiktok_etl.py:113} INFO - Checking token expiry: {'token': 'Bearer clt.2.2FPqi0MGZIXZZ3clzQTNg5HspN5-HWmf7L0NKoRX0BhEnZIjlUMjWt42QJ8VirRru6kD7hF-JzT4NzPJP7a0RA*0', 'expires_at': 1734557225.8813934}
[2024-12-18T19:27:06.898+0000] {tiktok_etl.py:132} INFO - Now in function tiktok_get_user_info, getting jadeanna
[2024-12-18T19:27:06.898+0000] {tiktok_etl.py:139} INFO - Requesting TikTok API with URL: https://open.tiktokapis.com/v2/research/user/info/, Headers: {'Authorization': 'Bearer clt.2.2FPqi0MGZIXZZ3clzQTNg5HspN5-HWmf7L0NKoRX0BhEnZIjlUMjWt42QJ8VirRru6kD7hF-JzT4NzPJP7a0RA*0', 'Content-Type': 'application/json'}, Body: {'username': 'jadeanna'}
[2024-12-18T19:27:06.900+0000] {connectionpool.py:1051} DEBUG - Starting new HTTPS connection (1): open.tiktokapis.com:443
[2024-12-18T19:27:07.465+0000] {connectionpool.py:546} DEBUG - https://open.tiktokapis.com:443 "POST /v2/research/user/info/?fields=display_name%2Cbio_description%2Cis_verified%2Cfollower_count%2Cfollowing_count%2Clikes_count%2Cvideo_count HTTP/11" 200 293
[2024-12-18T19:27:07.467+0000] {tiktok_etl.py:142} INFO - Call is done...
[2024-12-18T19:27:07.468+0000] {tiktok_etl.py:149} INFO - Now in function tiktok_get_user_info, getting resp {'data': {'likes_count': 152866744, 'video_count': 2517, 'bio_description': '🧸 founder @bi yù \n🎙️ 1/4 @Confession Club \n💌 jadeanna@ad-venturestudios.com', 'display_name': 'Jade Anna', 'follower_count': 1786471, 'following_count': 1392, 'is_verified': True}, 'error': {'code': 'ok', 'message': '', 'log_id': '20241218192706B7F0EC61F322400CEB46'}}
[2024-12-18T19:27:07.469+0000] {logger.py:100} DEBUG - {"message": "Server selection started", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Standalone, rtt: 0.0017599500133655965>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}}
[2024-12-18T19:27:07.470+0000] {logger.py:100} DEBUG - {"message": "Server selection succeeded", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Standalone, rtt: 0.0017599500133655965>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:07.472+0000] {logger.py:100} DEBUG - {"clientId": {"$oid": "676322083e4ccfb0efc84642"}, "message": "Command started", "command": "{\"insert\": \"user_info\", \"ordered\": true, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"Omf/o55IRcWje3hlcw4jgA==\", \"subType\": \"04\"}}}, \"$db\": \"tiktok_db\", \"documents\": [{\"likes_count\": 152866744, \"video_count\": 2517, \"bio_description\": \"\\ud83e\\uddf8 founder @bi y\\u00f9 \\n\\ud83c\\udf99\\ufe0f 1/4 @Confession Club \\n\\ud83d\\udc8c jadeanna@ad-venturestudios.com\", \"display_name\": \"Jade Anna\", \"follower_count\": 1786471, \"following_count\": 1392, \"is_verified\": true, \"username\": \"jadeanna\", \"timestamp\": {\"$date\": \"2024-12-18T19:27:07.469Z\"}, \"_id\": {\"$oid\": \"6763220b1cbfed16a5c84644\"}}]}", "commandName": "insert", "databaseName": "tiktok_db", "requestId": 1189641421, "operationId": 1189641421, "driverConnectionId": 1, "serverConnectionId": 19, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:07.476+0000] {logger.py:100} DEBUG - {"clientId": {"$oid": "676322083e4ccfb0efc84642"}, "message": "Command succeeded", "durationMS": 4.007000000000001, "reply": "{\"n\": 1, \"ok\": 1.0}", "commandName": "insert", "databaseName": "tiktok_db", "requestId": 1189641421, "operationId": 1189641421, "driverConnectionId": 1, "serverConnectionId": 19, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:07.478+0000] {tiktok_etl.py:202} INFO - Data for jadeanna inserted into MongoDB successfully.
[2024-12-18T19:27:07.479+0000] {tiktok_etl.py:177} INFO - TIKTOK request All Other Exception
[2024-12-18T19:27:07.480+0000] {tiktok_etl.py:178} INFO - An unexpected error occurred: name 'file_path' is not defined
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_etl.py", line 158, in tiktok_get_user_info
    context['ti'].xcom_push(key=f'{username}_info_path', value=file_path)
                                                               ^^^^^^^^^
NameError: name 'file_path' is not defined
[2024-12-18T19:27:07.489+0000] {tiktok_dag.py:62} INFO - Successfully fetched data for username: jadeanna
[2024-12-18T19:27:07.490+0000] {tiktok_dag.py:59} INFO - Fetching data for username: feyenoord
[2024-12-18T19:27:07.494+0000] {tiktok_etl.py:113} INFO - Checking token expiry: {'token': 'Bearer clt.2.2FPqi0MGZIXZZ3clzQTNg5HspN5-HWmf7L0NKoRX0BhEnZIjlUMjWt42QJ8VirRru6kD7hF-JzT4NzPJP7a0RA*0', 'expires_at': 1734557225.8813934}
[2024-12-18T19:27:07.496+0000] {tiktok_etl.py:132} INFO - Now in function tiktok_get_user_info, getting feyenoord
[2024-12-18T19:27:07.498+0000] {tiktok_etl.py:139} INFO - Requesting TikTok API with URL: https://open.tiktokapis.com/v2/research/user/info/, Headers: {'Authorization': 'Bearer clt.2.2FPqi0MGZIXZZ3clzQTNg5HspN5-HWmf7L0NKoRX0BhEnZIjlUMjWt42QJ8VirRru6kD7hF-JzT4NzPJP7a0RA*0', 'Content-Type': 'application/json'}, Body: {'username': 'feyenoord'}
[2024-12-18T19:27:07.500+0000] {connectionpool.py:1051} DEBUG - Starting new HTTPS connection (1): open.tiktokapis.com:443
[2024-12-18T19:27:07.836+0000] {connectionpool.py:546} DEBUG - https://open.tiktokapis.com:443 "POST /v2/research/user/info/?fields=display_name%2Cbio_description%2Cis_verified%2Cfollower_count%2Cfollowing_count%2Clikes_count%2Cvideo_count HTTP/11" 200 289
[2024-12-18T19:27:07.850+0000] {tiktok_etl.py:142} INFO - Call is done...
[2024-12-18T19:27:07.853+0000] {tiktok_etl.py:149} INFO - Now in function tiktok_get_user_info, getting resp {'data': {'follower_count': 1792448, 'following_count': 16, 'is_verified': True, 'likes_count': 33318832, 'video_count': 1104, 'bio_description': 'The official TikTok account of Feyenoord Rotterdam. \n\n𝙵𝚘𝚞𝚗𝚍𝚎𝚍 in 𝟷𝟿𝟶𝟾', 'display_name': 'Feyenoord'}, 'error': {'code': 'ok', 'message': '', 'log_id': '20241218192706049DEE37702C7F0E4316'}}
[2024-12-18T19:27:07.854+0000] {logger.py:100} DEBUG - {"message": "Server selection started", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Standalone, rtt: 0.0017599500133655965>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}}
[2024-12-18T19:27:07.869+0000] {logger.py:100} DEBUG - {"message": "Server selection succeeded", "selector": "<function writable_server_selector at 0x7f2a4f2cda80>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 676322083e4ccfb0efc84642, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Standalone, rtt: 0.0017599500133655965>]>", "clientId": {"$oid": "676322083e4ccfb0efc84642"}, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:07.872+0000] {logger.py:100} DEBUG - {"clientId": {"$oid": "676322083e4ccfb0efc84642"}, "message": "Command started", "command": "{\"insert\": \"user_info\", \"ordered\": true, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"Omf/o55IRcWje3hlcw4jgA==\", \"subType\": \"04\"}}}, \"$db\": \"tiktok_db\", \"documents\": [{\"follower_count\": 1792448, \"following_count\": 16, \"is_verified\": true, \"likes_count\": 33318832, \"video_count\": 1104, \"bio_description\": \"The official TikTok account of Feyenoord Rotterdam. \\n\\n\\ud835\\ude75\\ud835\\ude98\\ud835\\ude9e\\ud835\\ude97\\ud835\\ude8d\\ud835\\ude8e\\ud835\\ude8d in \\ud835\\udff7\\ud835\\udfff\\ud835\\udff6\\ud835\\udffe\", \"display_name\": \"Feyenoord\", \"username\": \"feyenoord\", \"timestamp\": {\"$date\": \"2024-12-18T19:27:07.854Z\"}, \"_id\": {\"$oid\": \"6763220b1cbfed16a5c84645\"}}]}", "commandName": "insert", "databaseName": "tiktok_db", "requestId": 1025202362, "operationId": 1025202362, "driverConnectionId": 1, "serverConnectionId": 19, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:07.874+0000] {logger.py:100} DEBUG - {"clientId": {"$oid": "676322083e4ccfb0efc84642"}, "message": "Command succeeded", "durationMS": 2.513, "reply": "{\"n\": 1, \"ok\": 1.0}", "commandName": "insert", "databaseName": "tiktok_db", "requestId": 1025202362, "operationId": 1025202362, "driverConnectionId": 1, "serverConnectionId": 19, "serverHost": "mongodb", "serverPort": 27017}
[2024-12-18T19:27:07.880+0000] {tiktok_etl.py:202} INFO - Data for feyenoord inserted into MongoDB successfully.
[2024-12-18T19:27:07.882+0000] {tiktok_etl.py:177} INFO - TIKTOK request All Other Exception
[2024-12-18T19:27:07.883+0000] {tiktok_etl.py:178} INFO - An unexpected error occurred: name 'file_path' is not defined
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_etl.py", line 158, in tiktok_get_user_info
    context['ti'].xcom_push(key=f'{username}_info_path', value=file_path)
                                                               ^^^^^^^^^
NameError: name 'file_path' is not defined
[2024-12-18T19:27:07.904+0000] {tiktok_dag.py:62} INFO - Successfully fetched data for username: feyenoord
[2024-12-18T19:27:07.905+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-18T19:27:07.907+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2024-12-18T19:27:07.954+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T19:27:07.956+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tiktok_dag, task_id=fetch_all_user_data, run_id=manual__2024-12-18T19:26:54.527334+00:00, execution_date=20241218T192654, start_date=20241218T192704, end_date=20241218T192707
[2024-12-18T19:27:07.992+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2024-12-18T19:27:08.062+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T19:27:08.095+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun tiktok_dag @ 2024-12-18 19:26:54.527334+00:00: manual__2024-12-18T19:26:54.527334+00:00, state:success, queued_at: 2024-12-18 19:26:54.612320+00:00. externally triggered: True>: 2 task(s)
[2024-12-18T19:27:08.096+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T19:27:08.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
