[2024-12-17T19:20:46.861+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-12-17T19:20:46.889+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2024-12-17T19:20:46.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T19:20:46.913+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-17T19:20:46.913+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-12-17T19:20:46.924+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-17T19:20:46.925+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-12-17T19:20:46.926+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]>
[2024-12-17T19:20:46.927+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-17T19:20:46.936+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-12-17T19:20:46.939+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-17T19:20:46.940+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-12-17T19:20:46.943+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [queued]>
[2024-12-17T19:20:46.944+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-17T19:20:46.963+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_all_user_data> on 2024-12-17 18:36:38.283747+00:00
[2024-12-17T19:20:46.979+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiktok_dag', 'fetch_all_user_data', 'manual__2024-12-17T18:36:38.283747+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/tiktok_dag.py', '--cfg-path', '/tmp/tmptiee0opi']
[2024-12-17T19:20:46.979+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-17T19:20:46.984+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask fetch_all_user_data
[2024-12-17T19:20:46.984+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2024-12-17T19:20:46.986+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7f3674785da0>]
[2024-12-17T19:20:47.060+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T18:36:38.283747+00:00 [running]> on host b221d1600292
[2024-12-17T19:20:47.137+0000] {taskinstance.py:2384} DEBUG - Clearing XCom data
[2024-12-17T19:20:47.156+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-12-17T19:20:47.187+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-12-17T19:20:47.205+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_dag' AIRFLOW_CTX_TASK_ID='fetch_all_user_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T18:36:38.283747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T18:36:38.283747+00:00'
[2024-12-17T19:20:47.206+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-12-17T19:20:47.207+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-12-17T19:20:47.208+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T19:20:47.228+0000] {tiktok_dag.py:51} INFO - Fetching data for all usernames...
[2024-12-17T19:20:47.241+0000] {tiktok_dag.py:53} INFO - Usernames pulled from XCom: ['mrbeast', 'jadeanna', 'feyenoord']
[2024-12-17T19:20:47.242+0000] {tiktok_dag.py:59} INFO - Fetching data for username: mrbeast
[2024-12-17T19:20:47.242+0000] {tiktok_etl.py:106} INFO - Checking token expiry: {'token': None, 'expires_at': None}
[2024-12-17T19:20:47.243+0000] {tiktok_dag.py:64} ERROR - Error fetching data for username mrbeast: 'TIKTOK'
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_dag.py", line 61, in fetch_all_user_data
    te.tiktok_get_user_info(username=username, output_dir=OUTPUT_DIR, **context)
  File "/opt/airflow/dags/tiktok_etl.py", line 119, in tiktok_get_user_info
    client_key = config["TIKTOK"]["CLIENT_KEY"]
                 ~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'TIKTOK'
[2024-12-17T19:20:47.252+0000] {tiktok_dag.py:59} INFO - Fetching data for username: jadeanna
[2024-12-17T19:20:47.252+0000] {tiktok_etl.py:106} INFO - Checking token expiry: {'token': None, 'expires_at': None}
[2024-12-17T19:20:47.253+0000] {tiktok_dag.py:64} ERROR - Error fetching data for username jadeanna: 'TIKTOK'
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_dag.py", line 61, in fetch_all_user_data
    te.tiktok_get_user_info(username=username, output_dir=OUTPUT_DIR, **context)
  File "/opt/airflow/dags/tiktok_etl.py", line 119, in tiktok_get_user_info
    client_key = config["TIKTOK"]["CLIENT_KEY"]
                 ~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'TIKTOK'
[2024-12-17T19:20:47.255+0000] {tiktok_dag.py:59} INFO - Fetching data for username: feyenoord
[2024-12-17T19:20:47.256+0000] {tiktok_etl.py:106} INFO - Checking token expiry: {'token': None, 'expires_at': None}
[2024-12-17T19:20:47.256+0000] {tiktok_dag.py:64} ERROR - Error fetching data for username feyenoord: 'TIKTOK'
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_dag.py", line 61, in fetch_all_user_data
    te.tiktok_get_user_info(username=username, output_dir=OUTPUT_DIR, **context)
  File "/opt/airflow/dags/tiktok_etl.py", line 119, in tiktok_get_user_info
    client_key = config["TIKTOK"]["CLIENT_KEY"]
                 ~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'TIKTOK'
[2024-12-17T19:20:47.259+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-17T19:20:47.259+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2024-12-17T19:20:47.270+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-17T19:20:47.270+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tiktok_dag, task_id=fetch_all_user_data, run_id=manual__2024-12-17T18:36:38.283747+00:00, execution_date=20241217T183638, start_date=20241217T192046, end_date=20241217T192047
[2024-12-17T19:20:47.285+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2024-12-17T19:20:47.322+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-17T19:20:47.342+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun tiktok_dag @ 2024-12-17 18:36:38.283747+00:00: manual__2024-12-17T18:36:38.283747+00:00, state:running, queued_at: 2024-12-17 18:36:38.318754+00:00. externally triggered: True>: 2 task(s)
[2024-12-17T19:20:47.343+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-17T19:20:47.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
